# https://docs.aws.amazon.com/codebuild/latest/userguide/build-spec-ref.html
# look for log output in the CodeBuild console
#
version: 0.2

phases:
  install:
    commands:
    - echo Nothing to do in the install phase...
  pre_build:
    commands:
    - echo Nothing to do in the pre_build phase...
  build:
    commands:
    - echo Build started on 'date'
    - echo CodeBuild source dir is $CODEBUILD_SRC_DIR
    - mvn install
  post_build:
    commands:
      - echo Nothing to do in the post-build phase...
# upload the outputs of the build to S3 bucket (Artifact_B)
artifacts:
  files:
    - '**/*.war'
    - 'scripts/*.sh'
    - appspec.yml
  discard-paths: yes
